# PRのラベルに応じてリリースノートのカテゴリで分類
changelog:
  exclude:
    authors:
    - github-actions
  categories:
  - title: ✨ New Features
    labels:
    - "feature"
  - title: 🐛 Bug Fixes
    labels:
      - "bug"
      - "fix"
  - title: 💥 Hotfix
    labels:
      - "hotfix"
  - title: ♻️ Refactoring
    labels:
      - "refactor"
  - title: 🛠 Other Changes
    labels:
    - "*"
