# Branch pattern
feature:
    - head-branch: ['^feature/', 'feat/']
fix:
    - head-branch: ['^fix/']
bug:
    - head-branch: [ '^bug/' ]
hotfix:
    - head-branch: ['^hotfix/']
refactor:
    - head-branch: [ '^refactor/' ]
