name: Create PR

on:
  pull_request:
      types:
        - closed
      branches:
        - dev

env:
  BASE_BRANCH: main
  DEV_BRANCH: dev

jobs:
  create_pr:
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
    steps:
      - uses: actions/checkout@master
        with:
            ref: ${{ env.BASE_BRANCH }}

      - name: Reset promotion branch
        run: |
          git fetch origin ${{ env.DEV_BRANCH }}:${{ env.DEV_BRANCH }}
          git reset --hard ${{ env.DEV_BRANCH }}

      - name: Create pull request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v6.0.4
        with:
            branch: ${{ env.DEV_BRANCH }}
            title: Mainブランチにマージ
