name: PR Labeler

run-name: ${{ github.event.pull_request.title }} / Run By @${{ github.actor}}

on:
  pull_request:
    branches-ignore:
        - main
        - prd
        - stg
    types: [opened]

jobs:
  auto-labeling-pr:
    if: github.event.pull_request.base.ref != 'stg' &&
        github.event.pull_request.base.ref != 'prd'
    runs-on: ubuntu-latest

    permissions:
        contents: read
        pull-requests: write

    timeout-minutes: 5

    steps:
        - uses: actions/labeler@v5
          with:
            configuration-path: .github/configs/labeler.yml
